### ISSUE TITLE
[1.0.1] Don't work with JBL quantum 600 (and any other sound device)

### ISSUE THREAD

**Issue by UnneRu** [targor/JBLRecover#1]
Error when starting app:
![image](https://user-images.githubusercontent.com/96411279/146731869-bd9e33ba-090c-4ea6-8549-785832d33fbb.png)
Selecting any device (Trying with my Quantum 600 and some other headphones and speakers).
![image](https://user-images.githubusercontent.com/96411279/146732030-c2e72c8d-ffdb-47e0-8929-39b869382384.png)
Then there is no change in device/track/playbacksignal even when i listening something (They always empty)
Win10 x64 21H1 with Russian language, updated framework etc.
Can you please help me with this or make something like "Just play sound every %N% mins" withut tracking?
Thanks!

**Comment by targor** [comment]
I maybe now fixed your problem and also published a new release 1.0.2. Please try it and tell if the problem is now solved.

**Comment by UnneRu** [comment]
It works with manual selecting.
Already got aimp with "every 9 mins play sound" shedule but this software better with tracking.
Thanks you a lot!

**Comment by targor** [comment]
You're welcome :)

**Comment by UnneRu** [comment]
I'm sorry but after some tests it still don't work. 
Now i got Device volume and Playbacksignal vol. active but nothing happens with "Track volume" (there must be your track when it played?) in 8 mins.
Tracking work:
![image](https://user-images.githubusercontent.com/96411279/146956584-af9a74ed-89b9-4c83-b63e-aa5136fe9526.png)

I set playtime for 3 mins (my headphones got 8 min shutdown delay) and track don't play in this 8 mins.
![image](https://user-images.githubusercontent.com/96411279/146956256-0bd49d87-fcf6-41f0-befe-c1d5c5703d9c.png)

**Comment by targor** [comment]
The track volume should work now (version release 1.0.3). The value is updated, as soon as the sine wave is played.

- Device volume displays the volume that is set in windows (volume level).
- Track volume ist the volume of the wav files that is played to prevent jbl from going into sleep
- Playback vol. ist the current volume level of the audiodevice's output.

**Comment by UnneRu** [comment]
1.0.3 still don't work.
Track does not play. I tried to track it in control panel but still nothing.
When i play this wav manually with aimp:
![image](https://user-images.githubusercontent.com/96411279/146964924-6aad11a3-51f1-464d-8c24-af41b1c97895.png)


When i stop all sounds and just wait (with 1 min playtime) same picture for 10 minutes:
![image](https://user-images.githubusercontent.com/96411279/146965140-6f7ab0d2-4251-4994-8f91-17bc36b01321.png)
No track volume so track don't played by software.

**Comment by targor** [comment]
Thanks for the input and patience. I have isolated another error, and fixed it. I tested it with one minute at my side and it seems to work now. Please test version 1.0.4. I also changed the guid of the setup, so this could run into problems on your side maybe.. to avoid errors uninstall the old version first, and then install the new one :).

**Comment by UnneRu** [comment]
Yes. It works now.
![image](https://user-images.githubusercontent.com/96411279/146971542-31889469-8a68-4747-8b4e-fc9ec52044c3.png)
Thanks!

**Comment by targor** [comment]
Finally :) .. Please open another issue if you run into other problems :).
